server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: menu-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/menus/**
          filters:
            - StripPrefix=1
        - id: stock-service
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/api/stock/**
        - id: commande-service
          uri: lb://COMMANDE-SERVICE
          predicates:
            - Path=/api/commandes/**
        - id: planning-service
          uri: lb://PLANNING-SERVICE
          predicates:
            - Path=/api/planning/**
        - id: statistiques-service
          uri: lb://STATISTIQUES-SERVICE
          predicates:
            - Path=/api/statistiques/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
